### ISSUE TITLE
Creation of AUR package

### ISSUE THREAD

**Issue by airon90** [MoonLightDE/MoonLightDE#14]
Hi, could someone create the [AUR](https://wiki.archlinux.org/index.php/AUR) packages for Arch Linux compilation? Thank you very much

**Comment by mckaygerhard** [comment]
packaging are not repated to project, are realted to each distribution.. so the ask must be in proper distribution forums or support..

in other ways, sometimes project provide packages for distributions, in that case if some distribution are not in the supported packages a contributor must made that job..

so close the issue due are unrelated, if any package will be provided shorlty, maybe/will be devuan/venenux only for now..
