### ISSUE TITLE
Display tasks into the side panel.

### ISSUE THREAD

**Issue by azubieta** [MoonLightDE/MoonLightDE#28]
In order to reduce the amount of floating windows and achieve a more clean DE we want to move the user thasks (copy, move, delete, zip, etc ) into the side panel just below the notifications.

**Comment by mckaygerhard** [comment]
filemanager-module and its copy/paste task, today as i described in #29 libfm are a library that implements all these operations (core only) so its better consume it, so lest close this issue due the staled status of the project and for more info see #29
