### ISSUE TITLE
Design and implement the Copy Task. 

### ISSUE THREAD

**Issue by azubieta** [MoonLightDE/MoonLightDE#30]
According to the proposed design this is implemented in a independent class that extends base class Task. Also this must be implemented as a QRunnable in order to non block the main thread with the reading an writhing procedures.

**Comment by mckaygerhard** [comment]
due the analisis made on #29 those task implementation are reinventation of the wheel, due if we implemented some tools/apps of other desktop are nonsense..

libfm are now a library that has some core of those task.. so close it and move all those discussion into the #29 due libfm are the lib that integrates those functionality (core-only)
