### ISSUE TITLE
Include 'checkinstall

### ISSUE THREAD

**Issue by koesherbacon** [MoonLightDE/MoonLightDE#36]
In your build insturctions, you might want to include 'checkinstall' as a dependancy.  I had to install it in order to build 'LibCppMicroServices' which was not easy at all since it's included in the default Ubuntu (and presumably most other distro's) default repo; but since I had to install it before proceeding it would save some time to add that in the beginning to save some time.

**Comment by azubieta** [comment]
Well checkinstall is not mandatory you can allays do 'make install' but we recommend it in order to not let trash around in your systems.  I added a hint at the build wiki page, please take a look at it.

**Comment by mckaygerhard** [comment]
this problem its related to the way of how the cmakefiles work in the libcppmicroservices.. documentation are currently updated to reflect that and will be solved with #38 so moving conversation if any and close it due inactivity.

At the moment of this answer, documentation was updated: https://github.com/MoonLightDE/MoonLightDE/wiki/Building-instructions

paste the documentation here due will be moved in near future:

Moonlight use a modified version of The C++ Micro Services library, version series 2.X (today C++ Micro services are in 3.X), provides a dynamic service registry and module system, partially based the OSGi Core Release 5 specifications, and a gcc with C++11 features its mandatory:

  1. Download the sources: `git clone https://github.com/MoonLightDE/CppMicroServices.git` (will be changed in near future)
  2. Create a folder to compile: `mkdir build;cd build`
  3. Configure the building of LibC++MicroServices: `cmake .. -DLIBRARY_INSTALL_DIR=/usr/local/lib`
  4. Build: `make`
  5. Install: `sudo make install`

**NOTE** the library has a customized cmake way of installation, so if you plan to distribute, must wait that issue #38 are solved or take manually the paths of the cmake files generated and the paths in the tool binary. for more info take a shot at the #38 

If you wish this library documentation to be generated before install, you must have installed `doxygen`, the generated documentation will be at: `/usr/local/share/CppMicroServices/doc/`.

**Comment by mckaygerhard** [comment]
now a default debian directory was added, now the library are staled and can installed normally using only prefix.. the debian/rules set the multiarch path in proper way

see #38
